/**
 * Anonymous name generator for users who want to hide their username on leaderboards.
 * Generates names in the format "Adjective Noun" (e.g., "Swift Falcon", "Clever Scholar").
 */

const ADJECTIVES = [
  'Swift',
  'Clever',
  'Mighty',
  'Brave',
  'Silent',
  'Golden',
  'Silver',
  'Crimson',
  'Azure',
  'Emerald',
  'Mystic',
  'Noble',
  'Fierce',
  'Gentle',
  'Bold',
  'Wise',
  'Lucky',
  'Cosmic',
  'Thunder',
  'Shadow',
  'Crystal',
  'Radiant',
  'Ancient',
  'Stellar',
  'Frozen',
  'Blazing',
  'Hidden',
  'Fearless',
  'Nimble',
  'Daring',
  'Serene',
  'Phantom',
  'Royal',
  'Lunar',
  'Solar',
  'Arcane',
  'Valiant',
  'Regal',
  'Primal',
  'Vivid',
  'Frosty',
  'Amber',
  'Jade',
  'Onyx',
  'Pearl',
  'Rustic',
  'Velvet',
  'Zephyr',
  'Astral',
  'Gleaming',
];

const NOUNS = [
  'Falcon',
  'Tiger',
  'Scholar',
  'Phoenix',
  'Dragon',
  'Wolf',
  'Eagle',
  'Bear',
  'Hawk',
  'Panther',
  'Lion',
  'Raven',
  'Fox',
  'Owl',
  'Stag',
  'Serpent',
  'Griffin',
  'Knight',
  'Sage',
  'Wanderer',
  'Voyager',
  'Pioneer',
  'Hunter',
  'Seeker',
  'Guardian',
  'Champion',
  'Warrior',
  'Ranger',
  'Wizard',
  'Titan',
  'Storm',
  'Flame',
  'Frost',
  'Wave',
  'Star',
  'Comet',
  'Nebula',
  'Meteor',
  'Sphinx',
  'Oracle',
  'Nomad',
  'Pilgrim',
  'Cipher',
  'Specter',
  'Shadow',
  'Echo',
  'Mirage',
  'Vertex',
  'Zenith',
  'Horizon',
];

/**
 * Generates a random anonymous display name.
 * @returns A string in the format "Adjective Noun"
 */
export function generateAnonymousName(): string {
  const adjective = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)];
  const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)];
  return `${adjective} ${noun}`;
}

