/**
 * Global phrase lists for daily games
 * Games will be created in order from these lists
 * Add new phrases to the bottom of the appropriate category
 */

export interface PhraseData {
  category: string;
  phrase: string;
}

/**
 * Lettered game phrases - these will be used in order
 * To add new games, simply append to this array
 */
export const LETTERED_PHRASES: PhraseData[] = [
  { category: 'Blockbuster Films', phrase: 'SPIDER MAN NO WAY HOME' },
  { category: 'Blockbuster Films', phrase: 'AVATAR THE WAY OF WATER' },
  { category: 'Blockbuster Films', phrase: 'TOP GUN MAVERICK' },
  { category: 'Blockbuster Films', phrase: 'BLACK PANTHER WAKANDA FOREVER' },
  { category: 'Blockbuster Films', phrase: 'THE BATMAN DARK KNIGHT' },
  { category: 'Blockbuster Films', phrase: 'DUNE PART TWO EPIC' },
  { category: 'Blockbuster Films', phrase: 'GUARDIANS OF THE GALAXY VOL THREE' },
  { category: 'Blockbuster Films', phrase: 'FAST X FAMILY SAGA' },
  { category: 'Blockbuster Films', phrase: 'SCREAM SIX HORROR SEQUEL' },
  { category: 'Blockbuster Films', phrase: 'JOHN WICK CHAPTER FOUR' },
  { category: 'Blockbuster Films', phrase: 'MISSION IMPOSSIBLE DEAD RECKONING' },
  { category: 'Blockbuster Films', phrase: 'OPPENHEIMER HISTORICAL DRAMA' },
  { category: 'Blockbuster Films', phrase: 'BARBIE PINK COMEDY MOVIE' },
  { category: 'Blockbuster Films', phrase: 'INDIANA JONES DIAL OF DESTINY' },

  { category: 'Classic Literature', phrase: 'WHERE THE CRAWDADS SING' },
  { category: 'Classic Literature', phrase: 'THE SEVEN HUSBANDS OF EVELYN HUGO' },
  { category: 'Classic Literature', phrase: 'EDUCATED TARA WESTOVER MEMOIR' },
  { category: 'Classic Literature', phrase: 'ATOMIC HABITS JAMES CLEAR' },
  { category: 'Classic Literature', phrase: 'THE MIDNIGHT LIBRARY MATT HAIG' },
  { category: 'Classic Literature', phrase: 'KLARA AND THE SUN KAZUO ISHIGURO' },
  { category: 'Classic Literature', phrase: 'THE INVISIBLE BRIDGE JULIE ORRINGER' },
  { category: 'Classic Literature', phrase: 'HAMNET MAGGIE O FARRELL NOVEL' },
  { category: 'Classic Literature', phrase: 'THE VANISHING HALF BRIT BENNETT' },
  { category: 'Classic Literature', phrase: 'CIRCE MADELINE MILLER MYTHOLOGY' },
  { category: 'Classic Literature', phrase: 'NORMAL PEOPLE SALLY ROONEY' },
  { category: 'Classic Literature', phrase: 'THE SILENT PATIENT ALEX MICHAELIDES' },
  { category: 'Classic Literature', phrase: 'IT ENDS WITH US COLLEEN HOOVER' },

  { category: 'Famous Catchphrases', phrase: 'MAY THE FORCE BE WITH YOU' },
  { category: 'Famous Catchphrases', phrase: 'I WILL BE BACK TERMINATOR' },
  { category: 'Famous Catchphrases', phrase: 'SHOW ME THE MONEY JERRY MAGUIRE' },
  { category: 'Famous Catchphrases', phrase: 'JUST KEEP SWIMMING FINDING NEMO' },
  { category: 'Famous Catchphrases', phrase: 'WINTER IS COMING GAME OF THRONES' },
  { category: 'Famous Catchphrases', phrase: 'TO INFINITY AND BEYOND BUZZ' },
  { category: 'Famous Catchphrases', phrase: 'HASTA LA VISTA BABY ARNOLD' },
  { category: 'Famous Catchphrases', phrase: 'NOBODY PUTS BABY IN A CORNER' },
  { category: 'Famous Catchphrases', phrase: 'I AM IRON MAN TONY STARK' },
  { category: 'Famous Catchphrases', phrase: 'WAKANDA FOREVER BLACK PANTHER' },
  { category: 'Famous Catchphrases', phrase: 'GREAT SCOTT BACK TO FUTURE' },
  { category: 'Famous Catchphrases', phrase: 'THAT IS WHAT SHE SAID OFFICE' },

  { category: 'Fast Food Items', phrase: 'MCDONALDS BIG MAC' },
  { category: 'Fast Food Items', phrase: 'BURGER KING WHOPPER' },
  { category: 'Fast Food Items', phrase: 'WENDYS BACONATOR' },
  { category: 'Fast Food Items', phrase: 'TACO BELL CRUNCHWRAP SUPREME' },
  { category: 'Fast Food Items', phrase: 'POPEYES SPICY CHICKEN SANDWICH' },
  { category: 'Fast Food Items', phrase: 'FIVE GUYS BACON CHEESEBURGER' },
  { category: 'Fast Food Items', phrase: 'IN N OUT ANIMAL STYLE' },
  { category: 'Fast Food Items', phrase: 'CHICK FIL A DELUXE SANDWICH' },
  { category: 'Fast Food Items', phrase: 'KFC ORIGINAL RECIPE' },
  { category: 'Fast Food Items', phrase: 'SUBWAY ITALIAN BMT' },
  { category: 'Fast Food Items', phrase: 'PIZZA HUT STUFFED CRUST' },
  { category: 'Fast Food Items', phrase: 'DOMINOS PEPPERONI PIZZA' },
  { category: 'Fast Food Items', phrase: 'DUNKIN ICED COFFEE' },

  { category: 'Video Game Titles', phrase: 'ELDEN RING' },
  { category: 'Video Game Titles', phrase: 'TEARS OF THE KINGDOM' },
  { category: 'Video Game Titles', phrase: 'GOD OF WAR RAGNAROK' },
  { category: 'Video Game Titles', phrase: 'HOGWARTS LEGACY' },
  { category: 'Video Game Titles', phrase: 'BALDURS GATE THREE' },
  { category: 'Video Game Titles', phrase: 'SPIDER MAN MILES MORALES' },
  { category: 'Video Game Titles', phrase: 'HORIZON FORBIDDEN WEST' },
  { category: 'Video Game Titles', phrase: 'HALO INFINITE' },
  { category: 'Video Game Titles', phrase: 'RESIDENT EVIL FOUR' },
  { category: 'Video Game Titles', phrase: 'CYBERPUNK TWENTY SEVENTY SEVEN' },
  { category: 'Video Game Titles', phrase: 'GENSHIN IMPACT' },
  { category: 'Video Game Titles', phrase: 'VALORANT' },
  { category: 'Video Game Titles', phrase: 'FALL GUYS' },

  { category: 'Netflix Original Shows', phrase: 'WEDNESDAY' },
  { category: 'Netflix Original Shows', phrase: 'STRANGER THINGS' },
  { category: 'Netflix Original Shows', phrase: 'SQUID GAME' },
  { category: 'Netflix Original Shows', phrase: 'BRIDGERTON' },
  { category: 'Netflix Original Shows', phrase: 'THE CROWN' },
  { category: 'Netflix Original Shows', phrase: 'OZARK' },
  { category: 'Netflix Original Shows', phrase: 'UMBRELLA ACADEMY' },
  { category: 'Netflix Original Shows', phrase: 'COBRA KAI' },
  { category: 'Netflix Original Shows', phrase: 'THE WITCHER' },
  { category: 'Netflix Original Shows', phrase: 'ORANGE IS THE NEW BLACK' },
  { category: 'Netflix Original Shows', phrase: 'HOUSE OF CARDS' },
  { category: 'Netflix Original Shows', phrase: 'NARCOS' },
  { category: 'Netflix Original Shows', phrase: 'DARK' },

  { category: 'Disney Movies', phrase: 'FROZEN' },
  { category: 'Disney Movies', phrase: 'MOANA' },
  { category: 'Disney Movies', phrase: 'ENCANTO' },
  { category: 'Disney Movies', phrase: 'TOY STORY' },
  { category: 'Disney Movies', phrase: 'THE LION KING' },
  { category: 'Disney Movies', phrase: 'FINDING NEMO' },
  { category: 'Disney Movies', phrase: 'THE INCREDIBLES' },
  { category: 'Disney Movies', phrase: 'COCO' },
  { category: 'Disney Movies', phrase: 'INSIDE OUT' },
  { category: 'Disney Movies', phrase: 'ZOOTOPIA' },
  { category: 'Disney Movies', phrase: 'BIG HERO SIX' },
  { category: 'Disney Movies', phrase: 'WRECK IT RALPH' },
  { category: 'Disney Movies', phrase: 'TANGLED' },

  { category: 'Pop Music Hits', phrase: 'AS IT WAS' },
  { category: 'Pop Music Hits', phrase: 'ANTI HERO' },
  { category: 'Pop Music Hits', phrase: 'FLOWERS' },
  { category: 'Pop Music Hits', phrase: 'UNHOLY' },
  { category: 'Pop Music Hits', phrase: 'CALM DOWN' },
  { category: 'Pop Music Hits', phrase: 'SHIVERS' },
  { category: 'Pop Music Hits', phrase: 'HEAT WAVES' },
  { category: 'Pop Music Hits', phrase: 'STAY' },
  { category: 'Pop Music Hits', phrase: 'GOOD FOUR U' },
  { category: 'Pop Music Hits', phrase: 'MONTERO' },
  { category: 'Pop Music Hits', phrase: 'PEACHES' },
  { category: 'Pop Music Hits', phrase: 'LEVITATING' },
  { category: 'Pop Music Hits', phrase: 'BLINDING LIGHTS' },

  { category: 'World Events', phrase: 'QATAR WORLD CUP' },
  { category: 'World Events', phrase: 'TOKYO OLYMPICS' },
  { category: 'World Events', phrase: 'JAMES WEBB TELESCOPE' },
  { category: 'World Events', phrase: 'QUEEN ELIZABETH JUBILEE' },
  { category: 'World Events', phrase: 'BITCOIN BOOM' },
  { category: 'World Events', phrase: 'SPACEX MARS MISSION' },
  { category: 'World Events', phrase: 'CLIMATE SUMMIT' },
  { category: 'World Events', phrase: 'CHATGPT LAUNCH' },
  { category: 'World Events', phrase: 'ELECTRIC VEHICLE BOOM' },
  { category: 'World Events', phrase: 'SOLAR ENERGY GROWTH' },
  { category: 'World Events', phrase: 'METAVERSE HYPE' },
  { category: 'World Events', phrase: 'TIKTOK TAKEOVER' },

  { category: 'Technology Products', phrase: 'IPHONE FOURTEEN PRO' },
  { category: 'Technology Products', phrase: 'SAMSUNG GALAXY' },
  { category: 'Technology Products', phrase: 'TESLA MODEL S' },
  { category: 'Technology Products', phrase: 'NINTENDO SWITCH' },
  { category: 'Technology Products', phrase: 'PLAYSTATION FIVE' },
  { category: 'Technology Products', phrase: 'XBOX SERIES X' },
  { category: 'Technology Products', phrase: 'MACBOOK PRO' },
  { category: 'Technology Products', phrase: 'AIRPODS PRO' },
  { category: 'Technology Products', phrase: 'GOOGLE PIXEL' },
  { category: 'Technology Products', phrase: 'META QUEST' },
  { category: 'Technology Products', phrase: 'AMAZON ALEXA' },
  { category: 'Technology Products', phrase: 'APPLE WATCH' },
  { category: 'Technology Products', phrase: 'ZOOM MEETINGS' },

  { category: 'Social Media Apps', phrase: 'TIKTOK' },
  { category: 'Social Media Apps', phrase: 'INSTAGRAM' },
  { category: 'Social Media Apps', phrase: 'SNAPCHAT' },
  { category: 'Social Media Apps', phrase: 'YOUTUBE' },
  { category: 'Social Media Apps', phrase: 'TWITTER' },
  { category: 'Social Media Apps', phrase: 'FACEBOOK' },
  { category: 'Social Media Apps', phrase: 'DISCORD' },
  { category: 'Social Media Apps', phrase: 'REDDIT' },
  { category: 'Social Media Apps', phrase: 'LINKEDIN' },
  { category: 'Social Media Apps', phrase: 'PINTEREST' },
  { category: 'Social Media Apps', phrase: 'TWITCH' },
  { category: 'Social Media Apps', phrase: 'CLUBHOUSE' },
  { category: 'Social Media Apps', phrase: 'BEREAL' },

  { category: 'Famous Landmarks', phrase: 'BURJ KHALIFA' },
  { category: 'Famous Landmarks', phrase: 'TIMES SQUARE' },
  { category: 'Famous Landmarks', phrase: 'HOLLYWOOD SIGN' },
  { category: 'Famous Landmarks', phrase: 'GOLDEN GATE BRIDGE' },
  { category: 'Famous Landmarks', phrase: 'MOUNT RUSHMORE' },
  { category: 'Famous Landmarks', phrase: 'SPACE NEEDLE' },
  { category: 'Famous Landmarks', phrase: 'STATUE OF LIBERTY' },
  { category: 'Famous Landmarks', phrase: 'GRAND CANYON' },
  { category: 'Famous Landmarks', phrase: 'YELLOWSTONE PARK' },
  { category: 'Famous Landmarks', phrase: 'NIAGARA FALLS' },
  { category: 'Famous Landmarks', phrase: 'BROOKLYN BRIDGE' },
  { category: 'Famous Landmarks', phrase: 'EMPIRE STATE BUILDING' },
  { category: 'Famous Landmarks', phrase: 'WASHINGTON MONUMENT' },
];

